### ISSUE TITLE
Content display issues with beta and dev PPA in ubuntu 21.04 and newer

### ISSUE THREAD

**Issue by TheBigK02** [saiarcot895/chromium-ubuntu-build#114]
Hi,

as requested, the bug report in here. May be someone can help with this. Since Upgrading to Version 91.0.4472.27 (Developer-Build) Ubuntu 21.04 (64-Bit) in the beta-ppa branch, I have troubles with viewing pages and also using for example the developer console.

In the console are no errors shown. It's probably something minor that causes it but I also tried with different user account. So changed settings or a browser plugin does not seem to cause the problem.

![Screenshot_20210510_082221](https://user-images.githubusercontent.com/50010925/117614658-e9abd600-b168-11eb-8e95-33cfe7efd6fa.png)
![Screenshot_20210505_091934](https://user-images.githubusercontent.com/50010925/117614660-ea446c80-b168-11eb-9686-4c0c8875d00f.png)

**Comment by LeDucDuBleuet** [comment]
Same here under Ubuntu 21.04.
Although when using the groovy beta ppa packages on hirsute hippo, it is working fine!

Same issue for Ungoogled Chromium under hirsute : https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/231

Thanks for looking into this and please keep up the good work!
:+1:

**Comment by saiarcot895** [comment]
I suspect that something in one of the HTML/JS tools/minifiers that the Chromium build runs is causing the output to be messed up on 21.04.

**Comment by LeDucDuBleuet** [comment]
Indeed this happens only with websites based on javascript frameworks.

**Comment by TheBigK02** [comment]
the 92 build doesnt work either. Same issue for me.

**Comment by TheBigK02** [comment]
is there something i can do to help narrow this down?

**Comment by worldofgeese** [comment]
This has been fixed over at https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/231

So looks like we're just waiting for those fixes to make it here

**Comment by ronjouch** [comment]
Same problem with freshly-built `92.0.4515.20-0ubuntu1~ppa1~21.04.1` (Hirsute): fonts fail to display in some webpages. Like with the previous build, using the `~20.10.1` package (Groovy) works

**Comment by saiarcot895** [comment]
I meant to ask how the new build was, but forgot to do so.

Thanks for the info. 

On June 3, 2021 9:02:42 PM CDT, Ronan Jouchet ***@***.***> wrote:
>Same problem with freshly-built `92.0.4515.20-0ubuntu1~ppa1~21.04.1`
>(Hirsute): fonts fail to display in some webpages. Like with the
>previous build, using the `~20.10.1` package (Groovy) works
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/saiarcot895/chromium-ubuntu-build/issues/114#issuecomment-854300808

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TheBigK02** [comment]
you mean the dev build right? still not good. same issue for me.

**Comment by saiarcot895** [comment]
I have a local fix for this, I think, but between the builds that I have published in the beta and dev PPAs and now, a good number of things have broken (audio doesn't play, scrolling after opening a Reddit post causes a crash).

Until I can locally verify that the browser will be stable, I won't be updating the PPA.

Also, Chromium 95 and newer will have schema and UI changes. What this means is that once I publish new builds, if you update to either the Beta or Dev PPA and then you try to revert to an older version, you will need to clear your local history file manually.

**Comment by ronjouch** [comment]
> I have a local fix for this, I think, but between the builds that I have published in the beta and dev PPAs and now, a good number of things have broken (audio doesn't play, scrolling after opening a Reddit post causes a crash).
> 
> Until I can locally verify that the browser will be stable, I won't be updating the PPA.

Thanks @saiarcot895. To add to the list of broken things: I'm staying on -dev 92-hirsute, because -dev 93-hirsute breaks Google Sheets (cells don't display, all sheets are empty).

Good luck getting a stable 95, thanks again for your work.

**Comment by saiarcot895** [comment]
In the Dev PPA, 95 is now available and functional for Ubuntu 21.04. Other Ubuntu versions should hopefully follow soon.

Note that regardless of Ubuntu version or hardware config, VAAPI hardware decoding will *not* work. This is due to Chromium now forcing the use of their Ozone graphics stack (which allows for separation of UI/rendering code with other code), and hardware decoding code not being implemented for that yet. There is a bug open [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1116701) for adding support for that, but I don't know when that will be implemented.

**Comment by ronjouch** [comment]
Problem is still present in `95.0.4638.17-0ubuntu1~ppa2~21.04.1` : most sites display properly, but Google Sheets is broken: text doesn't display, all sheets / cells are empty.

**Comment by saiarcot895** [comment]
Closing this issue, since the content display issues have been fixed.

Hardware acceleration should be working again on X11 (at least on AMD, can't confirm for Intel or Nvidia).
